artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view
  local_data_file: artifacts/data_ingestion/Chest-CT-Scan-data.zip
  unzip_dir: artifacts/data_ingestion
